/*
 * LAMV.java
 *
 * Created on 20 de Janeiro de 2005, 16:16
 */

package LAMV;

import java.io.File;
import java.util.*;
import javax.swing.filechooser.FileSystemView;
import javax.swing.tree.*;
import Dados.*;
import Janelas.*;
import Ferramentas.*;
import Sistema.*;
import Componentes.*;
import JExplorer.*;


/**
 *
 * @author  Gustavo
 */
public class LAMV extends javax.swing.JFrame {

    /**
     * Creates new form LAMV
     */
    public LAMV() {
        try {
	    javax.swing.UIManager.setLookAndFeel(javax.swing.UIManager.getSystemLookAndFeelClassName());
	} catch (Exception ex) { }
        configuracoes = new Configuracoes();
        je=new JExplorer(configuracoes);          

        initComponents();
        initVariaveisSistema();
       
        ScrollTree.setViewportView(je.tree); // -- AQUI
        
        TabelaDados.setModel( modelo );
        TabelaDados.setVisible(true);

        this.setSize(800,700);
        FSys.setFrameFinal( this );
    }
    
    private void initVariaveisSistema() {
        LDados = new Lista();
        LGraficos = new ListaGraf();
        Tree2 = new TreeSystem();
        modelo = new ModeloTabela();
        modelo.enableEdit();
        
        je.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PopUpExplorer.setVisible(true);
            }
        });
        leDisco d = new leDisco(configuracoes);
        try
        {
            d.le_boot();
        }
        catch(Exception e)
        {
            FSys.Msg("Erro", e.getMessage(),0);
        }
        for(int i = 0; i < configuracoes.enderecos.size(); i++)
        {
            JMenuMatrizesIniciais.add(new javax.swing.JMenuItem(configuracoes.enderecos.get(i).toString().trim()));
        }
        
        /** Inicializando as janelas */
        novam = new JDNovaM(this,true);
        doper = new DOper( this, true );
        dplot = new DPlot(this,true);
        ddec  = new DDec( this, true);
        dfiltros = new DFiltros(this,true);
        dcalibra = new DCalibra( this, true );
        dfourier = new DFourier( this, true );
    }
    
     /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        PopUpTable = new javax.swing.JPopupMenu();
        PopUpExplorer = new javax.swing.JPopupMenu();
        MIImportar = new javax.swing.JMenuItem();
        MIExcluir = new javax.swing.JMenuItem();
        JDRenomear = new javax.swing.JDialog();
        JLNovoNome = new javax.swing.JLabel();
        JTNovoNome = new javax.swing.JTextField();
        JBOkNovoNome = new javax.swing.JButton();
        BarraFerramenta = new javax.swing.JToolBar();
        BNovo = new javax.swing.JButton();
        BAbrir = new javax.swing.JButton();
        BOper = new javax.swing.JButton();
        BPlot = new javax.swing.JButton();
        BDecomp = new javax.swing.JButton();
        BFiltro = new javax.swing.JButton();
        BCalibra = new javax.swing.JButton();
        BFourier = new javax.swing.JButton();
        PCentro = new javax.swing.JPanel();
        SPCentro = new javax.swing.JSplitPane();
        TPCentro = new javax.swing.JTabbedPane();
        DPDados = new javax.swing.JDesktopPane();
        DPGraficos = new javax.swing.JDesktopPane();
        DPResult = new javax.swing.JDesktopPane();
        PEsc = new javax.swing.JPanel();
        SPEsc = new javax.swing.JSplitPane();
        PNorteEsq = new javax.swing.JPanel();
        PDiretorio = new javax.swing.JPanel();
        ScrollTree = new javax.swing.JScrollPane();
        PSulEsq = new javax.swing.JPanel();
        POperM = new javax.swing.JPanel();
        ScrollTab = new javax.swing.JScrollPane();
        TabelaDados = new javax.swing.JTable();
        PToolMat = new javax.swing.JPanel();
        BAdd = new javax.swing.JButton();
        BDel = new javax.swing.JButton();
        BInfo = new javax.swing.JButton();
        BarraMenu = new javax.swing.JMenuBar();
        MArquivo = new javax.swing.JMenu();
        MIAbrir = new javax.swing.JMenuItem();
        MISair = new javax.swing.JMenuItem();
        MEditar = new javax.swing.JMenu();
        MOper = new javax.swing.JMenu();
        JMIOperacoes = new javax.swing.JMenuItem();
        JMIDecompor = new javax.swing.JMenuItem();
        JMICalibrar = new javax.swing.JMenuItem();
        JMIPlotar = new javax.swing.JMenuItem();
        MConfig = new javax.swing.JMenu();
        MExplorer = new javax.swing.JMenu();
        MIFiltro = new javax.swing.JCheckBoxMenuItem();
        MDados = new javax.swing.JMenu();
        MINotacaoCientifica = new javax.swing.JCheckBoxMenuItem();
        MIJanelaUnica = new javax.swing.JCheckBoxMenuItem();
        MBoot = new javax.swing.JMenu();
        JMenuMatrizesIniciais = new javax.swing.JMenu();
        JMenuLimparMatrizes = new javax.swing.JMenuItem();
        MAjuda = new javax.swing.JMenu();

        MIImportar.setText("Importar");
        PopUpExplorer.add(MIImportar);

        MIExcluir.setText("Excluir");
        PopUpExplorer.add(MIExcluir);

        JDRenomear.getContentPane().setLayout(null);

        JDRenomear.setTitle("Renomear Dado");
        JLNovoNome.setText("Novo Nome:");
        JDRenomear.getContentPane().add(JLNovoNome);
        JLNovoNome.setBounds(10, 10, 70, 20);

        JDRenomear.getContentPane().add(JTNovoNome);
        JTNovoNome.setBounds(80, 10, 140, 20);

        JBOkNovoNome.setText("OK");
        JBOkNovoNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBOkNovoNomeActionPerformed(evt);
            }
        });

        JDRenomear.getContentPane().add(JBOkNovoNome);
        JBOkNovoNome.setBounds(230, 10, 50, 20);

        getContentPane().setLayout(new java.awt.BorderLayout(2, 2));

        setTitle("LAMV - Laborat\u00f3rio de An\u00e1lise Multivariada");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                exitForm(evt);
            }
        });

        BarraFerramenta.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        BNovo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagem/novo.gif")));
        BNovo.setToolTipText("Novo Dado");
        BNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BNovoActionPerformed(evt);
            }
        });

        BarraFerramenta.add(BNovo);

        BAbrir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagem/abrir.gif")));
        BAbrir.setToolTipText("Abrir Dado");
        BAbrir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BAbrirActionPerformed(evt);
            }
        });

        BarraFerramenta.add(BAbrir);

        BOper.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagem/oper.gif")));
        BOper.setToolTipText("Opera\u00e7\u00f5es");
        BOper.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BOperActionPerformed(evt);
            }
        });

        BarraFerramenta.add(BOper);

        BPlot.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagem/plot.gif")));
        BPlot.setToolTipText("Plotar");
        BPlot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BPlotActionPerformed(evt);
            }
        });

        BarraFerramenta.add(BPlot);

        BDecomp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagem/decompor.gif")));
        BDecomp.setToolTipText("Decompor");
        BDecomp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BDecompActionPerformed(evt);
            }
        });

        BarraFerramenta.add(BDecomp);

        BFiltro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagem/filtro.gif")));
        BFiltro.setToolTipText("FIltrar");
        BFiltro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BFiltroActionPerformed(evt);
            }
        });

        BarraFerramenta.add(BFiltro);

        BCalibra.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagem/calibra.gif")));
        BCalibra.setToolTipText("Calibra\u00e7\u00e3o");
        BCalibra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BCalibraActionPerformed(evt);
            }
        });

        BarraFerramenta.add(BCalibra);

        BFourier.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagem/fourier.gif")));
        BFourier.setToolTipText("Ferramentas de Fourier");
        BFourier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BFourierActionPerformed(evt);
            }
        });

        BarraFerramenta.add(BFourier);

        getContentPane().add(BarraFerramenta, java.awt.BorderLayout.NORTH);

        PCentro.setLayout(new java.awt.BorderLayout());

        PCentro.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        SPCentro.setDividerSize(7);
        SPCentro.setOneTouchExpandable(true);
        TPCentro.addTab("Dados", DPDados);

        TPCentro.addTab("Gr\u00e1ficos", DPGraficos);

        TPCentro.addTab("Resultados", DPResult);

        SPCentro.setRightComponent(TPCentro);

        PEsc.setLayout(new java.awt.BorderLayout());

        PEsc.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        PEsc.setMinimumSize(new java.awt.Dimension(10, 104));
        PEsc.setPreferredSize(new java.awt.Dimension(240, 185));
        SPEsc.setBorder(null);
        SPEsc.setDividerLocation(280);
        SPEsc.setDividerSize(7);
        SPEsc.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);
        SPEsc.setOneTouchExpandable(true);
        PNorteEsq.setLayout(new java.awt.BorderLayout());

        PDiretorio.setLayout(new java.awt.BorderLayout());

        PDiretorio.setBorder(javax.swing.BorderFactory.createTitledBorder("Explorer"));
        PDiretorio.setMinimumSize(new java.awt.Dimension(0, 50));
        PDiretorio.setPreferredSize(new java.awt.Dimension(230, 525));
        PDiretorio.add(ScrollTree, java.awt.BorderLayout.CENTER);

        PNorteEsq.add(PDiretorio, java.awt.BorderLayout.CENTER);

        SPEsc.setLeftComponent(PNorteEsq);

        PSulEsq.setLayout(new java.awt.BorderLayout());

        POperM.setLayout(new java.awt.BorderLayout());

        POperM.setBorder(javax.swing.BorderFactory.createTitledBorder("Dados"));
        POperM.setMinimumSize(new java.awt.Dimension(0, 50));
        POperM.setPreferredSize(new java.awt.Dimension(250, 300));
        ScrollTab.setPreferredSize(new java.awt.Dimension(215, 200));
        TabelaDados.setShowHorizontalLines(false);
        TabelaDados.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TabelaDadosMouseClicked(evt);
            }
        });

        ScrollTab.setViewportView(TabelaDados);

        POperM.add(ScrollTab, java.awt.BorderLayout.CENTER);

        BAdd.setText("Renomear");
        BAdd.setMargin(new java.awt.Insets(0, 10, 0, 10));
        BAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BAddActionPerformed(evt);
            }
        });

        PToolMat.add(BAdd);

        BDel.setText("Deletar");
        BDel.setMargin(new java.awt.Insets(0, 10, 0, 10));
        BDel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BDelActionPerformed(evt);
            }
        });

        PToolMat.add(BDel);

        BInfo.setText("Exibir");
        BInfo.setMargin(new java.awt.Insets(0, 10, 0, 10));
        BInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BInfoActionPerformed(evt);
            }
        });

        PToolMat.add(BInfo);

        POperM.add(PToolMat, java.awt.BorderLayout.SOUTH);

        PSulEsq.add(POperM, java.awt.BorderLayout.CENTER);

        SPEsc.setRightComponent(PSulEsq);

        PEsc.add(SPEsc, java.awt.BorderLayout.CENTER);

        SPCentro.setLeftComponent(PEsc);

        PCentro.add(SPCentro, java.awt.BorderLayout.CENTER);

        getContentPane().add(PCentro, java.awt.BorderLayout.CENTER);

        MArquivo.setText("Arquivo");
        MIAbrir.setText("Abrir dado");
        MIAbrir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MIAbrirActionPerformed(evt);
            }
        });

        MArquivo.add(MIAbrir);

        MISair.setText("Sair");
        MISair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MISairActionPerformed(evt);
            }
        });

        MArquivo.add(MISair);

        BarraMenu.add(MArquivo);

        MEditar.setText("Editar");
        BarraMenu.add(MEditar);

        MOper.setText("Ferramentas");
        JMIOperacoes.setText("Opera\u00e7\u00f5es");
        JMIOperacoes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JMIOperacoesActionPerformed(evt);
            }
        });

        MOper.add(JMIOperacoes);

        JMIDecompor.setText("Decompor");
        JMIDecompor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JMIDecomporActionPerformed(evt);
            }
        });

        MOper.add(JMIDecompor);

        JMICalibrar.setText("Calibrar");
        JMICalibrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JMICalibrarActionPerformed(evt);
            }
        });

        MOper.add(JMICalibrar);

        JMIPlotar.setText("Plotar");
        JMIPlotar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JMIPlotarActionPerformed(evt);
            }
        });

        MOper.add(JMIPlotar);

        BarraMenu.add(MOper);

        MConfig.setText("Configura\u00e7\u00f5es");
        MExplorer.setText("MaLab Explorer");
        MIFiltro.setSelected(true);
        MIFiltro.setText("Abilitar filtro de exibi\u00e7\u00e3o de arquivos");
        MIFiltro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MIFiltroActionPerformed(evt);
            }
        });

        MExplorer.add(MIFiltro);

        MConfig.add(MExplorer);

        MDados.setText("Dados");
        MINotacaoCientifica.setSelected(true);
        MINotacaoCientifica.setText("Usar nota\u00e7\u00e3o cient\u00edfica para exibir dados");
        MINotacaoCientifica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MINotacaoCientificaActionPerformed(evt);
            }
        });

        MDados.add(MINotacaoCientifica);

        MIJanelaUnica.setText("Utilizar uma \u00fanica janela de exibi\u00e7\u00e3o de dados");
        MDados.add(MIJanelaUnica);

        MConfig.add(MDados);

        MBoot.setText("Inicializa\u00e7\u00e3o");
        JMenuMatrizesIniciais.setText("Matrizes iniciais");
        MBoot.add(JMenuMatrizesIniciais);

        JMenuLimparMatrizes.setText("Limpar lista de matrizes carregadas no boot");
        JMenuLimparMatrizes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JMenuLimparMatrizesActionPerformed(evt);
            }
        });

        MBoot.add(JMenuLimparMatrizes);

        MConfig.add(MBoot);

        BarraMenu.add(MConfig);

        MAjuda.setText("Ajuda");
        BarraMenu.add(MAjuda);

        setJMenuBar(BarraMenu);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JBOkNovoNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBOkNovoNomeActionPerformed
// TODO add your handling code here:
        if( FSys.verificaNome( JTNovoNome.getText() ) ) {
            int x = TabelaDados.getSelectedRow();
            if( x < 0 ) {
                FSys.Msg("Erro!", "Selecione um dado na lista de dados!",0);
                return;
            }
            String nomeD = (String)modelo.getValueAt(x, 0);
            Dado _d = LDados.Procura(nomeD);
            if( _d == null ) {
                FSys.Msg("Erro!", "Erro interno!",0);
                return;
            }
            _d.setName( JTNovoNome.getText() );
            modelo.setValueAt( _d.getName(), x, 0 );
            JDRenomear.dispose();
        } else {
            FSys.Msg("Erro!", "Nome inválido.",0);
            return;
        }
    }//GEN-LAST:event_JBOkNovoNomeActionPerformed

    private void BAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BAddActionPerformed
// TODO add your handling code here:
        
        int x = TabelaDados.getSelectedRow();
        if( x < 0 ) {
            FSys.Msg("Erro!", "Selecione um dado na lista de dados!",0);
            return;
        }
        String nomeD = (String)modelo.getValueAt(x, 0);
        Dado _d = LDados.Procura(nomeD);
        if( _d == null ) {
            FSys.Msg("Erro!", "Erro interno!",0);
            return;
        }
        
        JDRenomear.setSize(310,80);
        FSys.centraliza(JDRenomear);
        JDRenomear.setVisible(true);
        
        JTNovoNome.setText( _d.getName() );
        JTNovoNome.selectAll();
    }//GEN-LAST:event_BAddActionPerformed

    private void JMIOperacoesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JMIOperacoesActionPerformed
// TODO add your handling code here:
        FSys.centraliza(doper);
        doper.refresh();
        doper.show();
    }//GEN-LAST:event_JMIOperacoesActionPerformed

    private void BFourierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BFourierActionPerformed
// TODO add your handling code here:
        FSys.centraliza(dfourier);
        dfourier.initVals();
        dfourier.show();
    }//GEN-LAST:event_BFourierActionPerformed

    private void MISairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MISairActionPerformed
// TODO add your handling code here:
        leDisco le = new leDisco(configuracoes);
        try
        {
            le.grava_boot();
        }
        catch(java.io.IOException e)
        {
            FSys.Msg("Erro", e.getMessage(),0);
        }
        System.exit(0);
    }//GEN-LAST:event_MISairActionPerformed

    private void MIAbrirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MIAbrirActionPerformed
// TODO add your handling code here:
        leDisco Disco = new leDisco(configuracoes);
        Disco.start();
    }//GEN-LAST:event_MIAbrirActionPerformed

    private void JMIPlotarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JMIPlotarActionPerformed
// TODO add your handling code here:
        FSys.centraliza(dplot);
        dplot.refresh();
        dplot.show();
    }//GEN-LAST:event_JMIPlotarActionPerformed

    private void JMICalibrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JMICalibrarActionPerformed
// TODO add your handling code here:
        dcalibra.initVals();
        FSys.centraliza(dcalibra);
        dcalibra.show();
    }//GEN-LAST:event_JMICalibrarActionPerformed

    private void JMIDecomporActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JMIDecomporActionPerformed
// TODO add your handling code here:
        FSys.centraliza(ddec);
        ddec.setVisible(true);
    }//GEN-LAST:event_JMIDecomporActionPerformed

    private void JMenuLimparMatrizesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JMenuLimparMatrizesActionPerformed
// TODO add your handling code here:
        JMenuMatrizesIniciais.removeAll();
        configuracoes.enderecos.clear();
    }//GEN-LAST:event_JMenuLimparMatrizesActionPerformed

    private void BFiltroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BFiltroActionPerformed
// TODO add your handling code here:
        dfiltros.initVals();
        FSys.centraliza(dfiltros);
        dfiltros.show();
    }//GEN-LAST:event_BFiltroActionPerformed

    private void MIFiltroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MIFiltroActionPerformed
        // TODO add your handling code here:
        if(MIFiltro.isSelected())
        {
            configuracoes.maLabExplorerFiltrar = true;
        }
        else 
            configuracoes.maLabExplorerFiltrar = false;
    }//GEN-LAST:event_MIFiltroActionPerformed

    private void MINotacaoCientificaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MINotacaoCientificaActionPerformed
        // TODO add your handling code here:
        if(MINotacaoCientifica.isSelected() )
            configuracoes.usarNotacaoCientifica = true;
        else
            configuracoes.usarNotacaoCientifica = false;
    }//GEN-LAST:event_MINotacaoCientificaActionPerformed

    private void BAbrirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BAbrirActionPerformed
        // TODO add your handling code here:
        leDisco Disco = new leDisco(configuracoes);
        Disco.start();
    }//GEN-LAST:event_BAbrirActionPerformed

    private void BOperActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BOperActionPerformed
        // TODO add your handling code here:
        FSys.centraliza(doper);
        doper.refresh();
        doper.show();
    }//GEN-LAST:event_BOperActionPerformed

    private void BCalibraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BCalibraActionPerformed
        // TODO add your handling code here:
        dcalibra.initVals();
        FSys.centraliza(dcalibra);
        dcalibra.show();
    }//GEN-LAST:event_BCalibraActionPerformed

    private void TabelaDadosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TabelaDadosMouseClicked
        // TODO add your handling code here:
        if( evt.getClickCount() != 2 )
            return;
        String n = (String)TabelaDados.getValueAt( TabelaDados.getSelectedRow(), 0 );
        if( n == null )
            return;
        Dado d = LDados.Procura( n );
        if( d == null )
            return;
        IFDado ifd = new IFDado(configuracoes, d );
        TPCentro.setSelectedIndex(0);
        DPDados.add( ifd, 0 );
        ifd.setVisible(true);
        DPDados.setSelectedFrame( ifd );
    }//GEN-LAST:event_TabelaDadosMouseClicked

    private void BDecompActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BDecompActionPerformed
        // TODO add your handling code here:
        FSys.centraliza(ddec);
        //d.setLocation( LAMV.System.FSys.getLocationCenter(this, d) );
        ddec.setVisible(true);
    }//GEN-LAST:event_BDecompActionPerformed

    private void BDelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BDelActionPerformed
        // TODO add your handling code here:
        int x = TabelaDados.getSelectedRow();
        if( x < 0 ) {
            FSys.Msg("Erro!", "Selecione um dado na lista de dados!",0);
            return;
        }
        String nomeD = (String)modelo.getValueAt(x, 0);
        Dado _d = LDados.Procura(nomeD);
        if( _d == null ) {
            FSys.Msg("Erro!", "Erro interno!",0);
            return;
        }
        LDados.Remove( nomeD );
        modelo.removeRow(x);
    }//GEN-LAST:event_BDelActionPerformed

    private void BInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BInfoActionPerformed
        // TODO add your handling code here:
        int x = TabelaDados.getSelectedRow();
        if( x < 0 ) {
            FSys.Msg("Erro!", "Selecione um dado na lista de dados!",0);
            //return;
        }
        //String nomeD = (String)modelo.getValueAt(x, 0);

        Dado _d;// = LDados.Procura(nomeD);
                
        Algebra alg = new Algebra();
        _d = alg.Elipse(2,2,10,10,3.14/2,0.01);
        IFGrafico g = new IFGrafico();
        _d.setVerRetas(true);
        TPCentro.setSelectedIndex(1);
        DPGraficos.add( g , 0 );
        g.Plot(_d);
        g.show();
    }//GEN-LAST:event_BInfoActionPerformed

    private void BPlotActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BPlotActionPerformed
        // TODO add your handling code here:
        FSys.centraliza(dplot);
        dplot.refresh();
        dplot.show();
    }//GEN-LAST:event_BPlotActionPerformed

    private void BNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BNovoActionPerformed
        // TODO add your handling code here:
        FSys.centraliza(novam);
        novam.show();
    }//GEN-LAST:event_BNovoActionPerformed

    /** Exit the Application */
    private void exitForm(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_exitForm
        leDisco le = new leDisco(configuracoes);
        try
        {
            le.grava_boot();
        }
        catch(java.io.IOException e)
        {
            FSys.Msg("Erro", e.getMessage(),0);
        }
        System.exit(0);
    }//GEN-LAST:event_exitForm
    
    /**
     * @param args the command line arguments
     */

    public static void main(String args[]) {
        new LAMV().show();
        Matriz M = new Matriz(1,1);
    }
    
    private static class DirNode extends DefaultMutableTreeNode {
	DirNode(File dir) {
	    super(dir);
            File d = dir;
        }
	public File getDir() {
	    return (File)userObject;
	}
	public int getChildCount() {
	    populateChildren();
	    return super.getChildCount();
	}
	public Enumeration children() {
	    populateChildren();
	    return super.children();
	}
	public boolean isLeaf() {
	    return false;
	}
	private void populateChildren() {
	    if (children == null) {
		File[] files = fsv.getFiles(getDir(), true);
		Arrays.sort(files);
		for (int i = 0; i < files.length; i++) {
		    File f = files[i];
		    if (fsv.isTraversable(f).booleanValue()) {
			this.insert(new DirNode(f),
			       (children == null) ? 0 : children.size());
		    }
/*                    else {
                        this.add(new DefaultMutableTreeNode(f.getName()));
                    }*/
		}
	    }
	}
	public String toString() {
	    return fsv.getSystemDisplayName(getDir());
	}
	public boolean equals(Object o) {
	    return (o instanceof DirNode &&
		    userObject.equals(((DirNode)o).userObject));
	}
    }
    
    private static FileSystemView fsv = FileSystemView.getFileSystemView();
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BAbrir;
    private javax.swing.JButton BAdd;
    private javax.swing.JButton BCalibra;
    private javax.swing.JButton BDecomp;
    private javax.swing.JButton BDel;
    private javax.swing.JButton BFiltro;
    private javax.swing.JButton BFourier;
    private javax.swing.JButton BInfo;
    private javax.swing.JButton BNovo;
    private javax.swing.JButton BOper;
    private javax.swing.JButton BPlot;
    private javax.swing.JToolBar BarraFerramenta;
    private javax.swing.JMenuBar BarraMenu;
    public static javax.swing.JDesktopPane DPDados;
    public static javax.swing.JDesktopPane DPGraficos;
    public static javax.swing.JDesktopPane DPResult;
    private javax.swing.JButton JBOkNovoNome;
    private javax.swing.JDialog JDRenomear;
    private javax.swing.JLabel JLNovoNome;
    private javax.swing.JMenuItem JMICalibrar;
    private javax.swing.JMenuItem JMIDecompor;
    private javax.swing.JMenuItem JMIOperacoes;
    private javax.swing.JMenuItem JMIPlotar;
    private javax.swing.JMenuItem JMenuLimparMatrizes;
    private javax.swing.JMenu JMenuMatrizesIniciais;
    private javax.swing.JTextField JTNovoNome;
    private javax.swing.JMenu MAjuda;
    private javax.swing.JMenu MArquivo;
    private javax.swing.JMenu MBoot;
    private javax.swing.JMenu MConfig;
    private javax.swing.JMenu MDados;
    private javax.swing.JMenu MEditar;
    private javax.swing.JMenu MExplorer;
    private javax.swing.JMenuItem MIAbrir;
    private javax.swing.JMenuItem MIExcluir;
    private javax.swing.JCheckBoxMenuItem MIFiltro;
    private javax.swing.JMenuItem MIImportar;
    private javax.swing.JCheckBoxMenuItem MIJanelaUnica;
    private javax.swing.JCheckBoxMenuItem MINotacaoCientifica;
    private javax.swing.JMenuItem MISair;
    private javax.swing.JMenu MOper;
    private javax.swing.JPanel PCentro;
    private javax.swing.JPanel PDiretorio;
    private javax.swing.JPanel PEsc;
    private javax.swing.JPanel PNorteEsq;
    private javax.swing.JPanel POperM;
    private javax.swing.JPanel PSulEsq;
    private javax.swing.JPanel PToolMat;
    private javax.swing.JPopupMenu PopUpExplorer;
    private javax.swing.JPopupMenu PopUpTable;
    private javax.swing.JSplitPane SPCentro;
    private javax.swing.JSplitPane SPEsc;
    private javax.swing.JScrollPane ScrollTab;
    private javax.swing.JScrollPane ScrollTree;
    public static javax.swing.JTabbedPane TPCentro;
    private javax.swing.JTable TabelaDados;
    // End of variables declaration//GEN-END:variables

    private TreeSystem Tree2;
    public static Lista LDados;
    public static ListaGraf LGraficos;
    public static ModeloTabela modelo;
    public Configuracoes configuracoes;
    private JExplorer je;

    private JDNovaM novam;
    private DOper doper;
    private DPlot dplot;
    private DDec  ddec;
    private DFiltros dfiltros;
    private DCalibra dcalibra;
    private DFourier dfourier;
}