/*
 * IFMatriz.java
 *
 * Created on 3 de Março de 2005, 20:52
 */
package Janelas;
/**
 *
 * @author  Gustavo
 */

import Componentes.Grafico.*;
import Dados.*;
import Componentes.ModeloTabelaLista;
import Sistema.FSys;
import java.io.*;
import java.io.FileOutputStream  ;
import javax.swing.*;
import javax.swing.filechooser.FileFilter;
import Sistema.leDisco;
import java.util.StringTokenizer;

public class IFGrafico extends javax.swing.JInternalFrame {
    
    /** Creates new form IFMatriz */
    public IFGrafico() {
        this("Gráfico");
    }
    public IFGrafico( String nome ) {
        initComponents();

        this.Nome = nome;
        this.setTitle(nome);        

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        this.setSize(400,200);
        GG = new PanelGrafico(this);
        
        initVar();

        this.getContentPane().add("Center", GG);
        
        this.addInternalFrameListener( new javax.swing.event.InternalFrameAdapter() {
            public void windowClosing(javax.swing.event.InternalFrameEvent evt) {
                Sistema.FSys.Msg("","",0);
                dispose();
            }
        });
        
        modelo = new ModeloTabelaLista();
        TDados.setModel( modelo );
    }

    private void initVar() {
        PCorFundo.setBackground( GG.getCorFundo() );
        PCorGrid.setBackground( GG.getCorGrid() );
        PCorGraf.setCursor(java.awt.Cursor.getPredefinedCursor(java.awt.Cursor.HAND_CURSOR));
        PCorGrid.setCursor(java.awt.Cursor.getPredefinedCursor(java.awt.Cursor.HAND_CURSOR));
        PCorFundo.setCursor(java.awt.Cursor.getPredefinedCursor(java.awt.Cursor.HAND_CURSOR));
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        DConfig = new javax.swing.JDialog();
        POutros = new javax.swing.JPanel();
        LCorG1 = new javax.swing.JLabel();
        LLargG1 = new javax.swing.JLabel();
        PCorFundo = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        TFLabelY = new javax.swing.JTextField();
        TFLabelX = new javax.swing.JTextField();
        PCorGrid = new javax.swing.JPanel();
        CBMostrarX = new javax.swing.JCheckBox();
        CBMostrarY = new javax.swing.JCheckBox();
        CBMostrarLegenda = new javax.swing.JCheckBox();
        CBExibirLabelX = new javax.swing.JCheckBox();
        CBExibirLabelY = new javax.swing.JCheckBox();
        jLabel1 = new javax.swing.JLabel();
        TFContX = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        TFContY = new javax.swing.JTextField();
        CBExibirContX = new javax.swing.JCheckBox();
        CBExibirContY = new javax.swing.JCheckBox();
        CBMostrarGrid = new javax.swing.JCheckBox();
        jPanel = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        PCorGraf = new javax.swing.JPanel();
        CBLinhas = new javax.swing.JCheckBox();
        CBPontos = new javax.swing.JCheckBox();
        TBQuadrado = new javax.swing.JToggleButton();
        TBCirculo = new javax.swing.JToggleButton();
        PListaDados = new javax.swing.JPanel();
        SPDados = new javax.swing.JScrollPane();
        TDados = new javax.swing.JTable();
        BExcluir = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        buttonGroup1 = new javax.swing.ButtonGroup();
        Toobar = new javax.swing.JToolBar();
        BSalvarG = new javax.swing.JButton();
        Separador0 = new javax.swing.JSeparator();
        BAuto = new javax.swing.JButton();
        BAjustar = new javax.swing.JButton();
        BZoomIn = new javax.swing.JButton();
        BZoomOut = new javax.swing.JButton();
        Separador1 = new javax.swing.JSeparator();
        BZinH = new javax.swing.JButton();
        BZoutH = new javax.swing.JButton();
        BZinV = new javax.swing.JButton();
        BZoutV = new javax.swing.JButton();
        Separador2 = new javax.swing.JSeparator();
        BProxP = new javax.swing.JButton();
        BAntP = new javax.swing.JButton();
        TBConfig = new javax.swing.JToggleButton();
        Separador3 = new javax.swing.JSeparator();
        LabelPosMouse = new javax.swing.JLabel();
        PCentro = new javax.swing.JPanel();

        DConfig.getContentPane().setLayout(null);

        DConfig.setModal(true);
        DConfig.setName("DConfig");
        POutros.setLayout(null);

        POutros.setBorder(javax.swing.BorderFactory.createTitledBorder("Op\u00e7\u00f5es"));
        LCorG1.setText("Cor fundo:");
        POutros.add(LCorG1);
        LCorG1.setBounds(10, 20, 70, 20);

        LLargG1.setText("Cor Grid:");
        POutros.add(LLargG1);
        LLargG1.setBounds(10, 40, 70, 20);

        PCorFundo.setBackground(FSys.COR_FUNDO_PADRAO);
        PCorFundo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        PCorFundo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PCorFundoMouseClicked(evt);
            }
        });

        POutros.add(PCorFundo);
        PCorFundo.setBounds(80, 19, 20, 20);

        jLabel3.setText("Label x:");
        POutros.add(jLabel3);
        jLabel3.setBounds(130, 20, 50, 14);

        jLabel5.setText("Label y:");
        POutros.add(jLabel5);
        jLabel5.setBounds(130, 60, 50, 14);

        TFLabelY.setText("Eixo y");
        TFLabelY.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                TFLabelYFocusLost(evt);
            }
        });

        POutros.add(TFLabelY);
        TFLabelY.setBounds(130, 75, 110, 19);

        TFLabelX.setText("Eixo x");
        TFLabelX.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                TFLabelXFocusLost(evt);
            }
        });

        POutros.add(TFLabelX);
        TFLabelX.setBounds(130, 35, 110, 19);

        PCorGrid.setBackground(FSys.COR_GRID_PADRAO);
        PCorGrid.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        PCorGrid.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PCorGridMouseClicked(evt);
            }
        });

        POutros.add(PCorGrid);
        PCorGrid.setBounds(80, 41, 20, 20);

        CBMostrarX.setSelected(true);
        CBMostrarX.setText("Mostrar eixo X");
        CBMostrarX.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CBMostrarXActionPerformed(evt);
            }
        });

        POutros.add(CBMostrarX);
        CBMostrarX.setBounds(10, 90, 120, 23);

        CBMostrarY.setSelected(true);
        CBMostrarY.setText("Mostrar eixo Y");
        CBMostrarY.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CBMostrarYActionPerformed(evt);
            }
        });

        POutros.add(CBMostrarY);
        CBMostrarY.setBounds(10, 110, 120, 23);

        CBMostrarLegenda.setText("Exibir Legenda");
        CBMostrarLegenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CBMostrarLegendaActionPerformed(evt);
            }
        });

        POutros.add(CBMostrarLegenda);
        CBMostrarLegenda.setBounds(10, 130, 120, 23);

        CBExibirLabelX.setText("Exibir");
        CBExibirLabelX.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CBExibirLabelXActionPerformed(evt);
            }
        });

        POutros.add(CBExibirLabelX);
        CBExibirLabelX.setBounds(240, 35, 60, 23);

        CBExibirLabelY.setText("Exibir");
        CBExibirLabelY.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CBExibirLabelYActionPerformed(evt);
            }
        });

        POutros.add(CBExibirLabelY);
        CBExibirLabelY.setBounds(240, 75, 60, 23);

        jLabel1.setText("Contagem X:");
        POutros.add(jLabel1);
        jLabel1.setBounds(15, 170, 70, 20);

        TFContX.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        TFContX.setText("4");
        TFContX.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                TFContXFocusLost(evt);
            }
        });

        POutros.add(TFContX);
        TFContX.setBounds(85, 170, 30, 19);

        jButton2.setText("Restaurar Padr\u00e3o");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        POutros.add(jButton2);
        jButton2.setBounds(15, 230, 130, 23);

        jLabel2.setText("Contagem Y:");
        POutros.add(jLabel2);
        jLabel2.setBounds(15, 195, 70, 20);

        TFContY.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        TFContY.setText("4");
        TFContY.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                TFContYFocusLost(evt);
            }
        });

        POutros.add(TFContY);
        TFContY.setBounds(85, 195, 30, 19);

        CBExibirContX.setSelected(true);
        CBExibirContX.setText("Exibir");
        CBExibirContX.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CBExibirContXActionPerformed(evt);
            }
        });

        POutros.add(CBExibirContX);
        CBExibirContX.setBounds(115, 170, 60, 23);

        CBExibirContY.setSelected(true);
        CBExibirContY.setText("Exibir");
        CBExibirContY.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CBExibirContYActionPerformed(evt);
            }
        });

        POutros.add(CBExibirContY);
        CBExibirContY.setBounds(115, 195, 60, 23);

        CBMostrarGrid.setSelected(true);
        CBMostrarGrid.setText("Exibir Grid");
        CBMostrarGrid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CBMostrarGridActionPerformed(evt);
            }
        });

        POutros.add(CBMostrarGrid);
        CBMostrarGrid.setBounds(10, 70, 120, 23);

        DConfig.getContentPane().add(POutros);
        POutros.setBounds(200, 5, 310, 310);

        jPanel.setLayout(null);

        jPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Gr\u00e1fico/Componente"));
        jLabel6.setText("Cor do Gr\u00e1fico:");
        jPanel.add(jLabel6);
        jLabel6.setBounds(10, 20, 90, 14);

        PCorGraf.setBackground(new java.awt.Color(255, 255, 255));
        PCorGraf.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        PCorGraf.setEnabled(false);
        PCorGraf.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PCorGrafMouseClicked(evt);
            }
        });

        jPanel.add(PCorGraf);
        PCorGraf.setBounds(100, 20, 20, 20);

        CBLinhas.setSelected(true);
        CBLinhas.setText("Linhas");
        CBLinhas.setEnabled(false);
        CBLinhas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CBLinhasActionPerformed(evt);
            }
        });

        jPanel.add(CBLinhas);
        CBLinhas.setBounds(10, 50, 70, 23);

        CBPontos.setSelected(true);
        CBPontos.setText("Pontos");
        CBPontos.setEnabled(false);
        CBPontos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CBPontosActionPerformed(evt);
            }
        });

        jPanel.add(CBPontos);
        CBPontos.setBounds(10, 70, 70, 23);

        buttonGroup1.add(TBQuadrado);
        TBQuadrado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagem/Pontos/quadrado.gif")));
        TBQuadrado.setSelected(true);
        TBQuadrado.setToolTipText("Pontos");
        TBQuadrado.setEnabled(false);
        TBQuadrado.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagem/Pontos/quadrado_focus.gif")));
        TBQuadrado.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagem/Pontos/quadrado_focus.gif")));
        TBQuadrado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TBQuadradoActionPerformed(evt);
            }
        });

        jPanel.add(TBQuadrado);
        TBQuadrado.setBounds(80, 70, 20, 20);

        buttonGroup1.add(TBCirculo);
        TBCirculo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagem/Pontos/cir.gif")));
        TBCirculo.setToolTipText("Triangulo");
        TBCirculo.setEnabled(false);
        TBCirculo.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagem/Pontos/cir_focus.gif")));
        TBCirculo.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagem/Pontos/cir_focus.gif")));
        TBCirculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TBCirculoActionPerformed(evt);
            }
        });

        jPanel.add(TBCirculo);
        TBCirculo.setBounds(110, 70, 20, 20);

        DConfig.getContentPane().add(jPanel);
        jPanel.setBounds(5, 215, 190, 100);

        PListaDados.setLayout(new java.awt.BorderLayout());

        PListaDados.setBorder(javax.swing.BorderFactory.createTitledBorder("Lista de Componentes"));
        TDados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nome"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        TDados.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TDadosMouseClicked(evt);
            }
        });

        SPDados.setViewportView(TDados);

        PListaDados.add(SPDados, java.awt.BorderLayout.CENTER);

        BExcluir.setText("Excluir");
        BExcluir.setMargin(new java.awt.Insets(2, 2, 2, 2));
        BExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BExcluirActionPerformed(evt);
            }
        });

        PListaDados.add(BExcluir, java.awt.BorderLayout.SOUTH);

        DConfig.getContentPane().add(PListaDados);
        PListaDados.setBounds(5, 5, 190, 210);

        jButton1.setText("OK");
        jButton1.setMargin(new java.awt.Insets(2, 2, 2, 2));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        DConfig.getContentPane().add(jButton1);
        jButton1.setBounds(440, 315, 65, 30);

        Toobar.setFloatable(false);
        BSalvarG.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagem/salvar.gif")));
        BSalvarG.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BSalvarGActionPerformed(evt);
            }
        });

        Toobar.add(BSalvarG);

        Separador0.setOrientation(javax.swing.SwingConstants.VERTICAL);
        Separador0.setToolTipText("");
        Separador0.setMaximumSize(new java.awt.Dimension(1, 150));
        Toobar.add(Separador0);

        BAuto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagem/Grafico/ajustar_zoom.gif")));
        BAuto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BAutoActionPerformed(evt);
            }
        });

        Toobar.add(BAuto);

        BAjustar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagem/Grafico/autoajuste.gif")));
        BAjustar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BAjustarActionPerformed(evt);
            }
        });

        Toobar.add(BAjustar);

        BZoomIn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagem/Grafico/zoom_in.gif")));
        BZoomIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BZoomInActionPerformed(evt);
            }
        });

        Toobar.add(BZoomIn);

        BZoomOut.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagem/Grafico/zoom_out.gif")));
        BZoomOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BZoomOutActionPerformed(evt);
            }
        });

        Toobar.add(BZoomOut);

        Separador1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        Separador1.setToolTipText("");
        Separador1.setMaximumSize(new java.awt.Dimension(1, 150));
        Toobar.add(Separador1);

        BZinH.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagem/Grafico/zoom_in_h.gif")));
        BZinH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BZinHActionPerformed(evt);
            }
        });

        Toobar.add(BZinH);

        BZoutH.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagem/Grafico/zoom_out_h.gif")));
        BZoutH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BZoutHActionPerformed(evt);
            }
        });

        Toobar.add(BZoutH);

        BZinV.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagem/Grafico/zoom_in_v.gif")));
        BZinV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BZinVActionPerformed(evt);
            }
        });

        Toobar.add(BZinV);

        BZoutV.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagem/Grafico/zoom_out_v.gif")));
        BZoutV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BZoutVActionPerformed(evt);
            }
        });

        Toobar.add(BZoutV);

        Separador2.setOrientation(javax.swing.SwingConstants.VERTICAL);
        Separador2.setMaximumSize(new java.awt.Dimension(1, 100));
        Toobar.add(Separador2);

        BProxP.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagem/Grafico/prox_ponto.gif")));
        Toobar.add(BProxP);

        BAntP.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagem/Grafico/ant_ponto.gif")));
        BAntP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BAntPActionPerformed(evt);
            }
        });

        Toobar.add(BAntP);

        TBConfig.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagem/config.png")));
        TBConfig.setMaximumSize(new java.awt.Dimension(60, 27));
        TBConfig.setMinimumSize(new java.awt.Dimension(60, 27));
        TBConfig.setPreferredSize(new java.awt.Dimension(60, 27));
        TBConfig.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TBConfigActionPerformed(evt);
            }
        });

        Toobar.add(TBConfig);

        Separador3.setOrientation(javax.swing.SwingConstants.VERTICAL);
        Separador3.setMaximumSize(new java.awt.Dimension(1, 100));
        Separador3.setPreferredSize(null);
        Toobar.add(Separador3);

        LabelPosMouse.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LabelPosMouse.setText("[ 0 , 0 ]");
        LabelPosMouse.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        LabelPosMouse.setMaximumSize(new java.awt.Dimension(150, 14));
        LabelPosMouse.setMinimumSize(new java.awt.Dimension(150, 14));
        Toobar.add(LabelPosMouse);

        getContentPane().add(Toobar, java.awt.BorderLayout.NORTH);

        PCentro.setLayout(null);

        PCentro.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        getContentPane().add(PCentro, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TFContYFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_TFContYFocusLost
// TODO add your handling code here:
        GG.setContY( Integer.valueOf(TFContY.getText()).intValue() );
    }//GEN-LAST:event_TFContYFocusLost

    private void TFContXFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_TFContXFocusLost
// TODO add your handling code here:
        GG.setContX( Integer.valueOf(TFContX.getText()).intValue() );
    }//GEN-LAST:event_TFContXFocusLost

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
// TODO add your handling code here:
        PCorFundo.setBackground(FSys.COR_FUNDO_PADRAO);
        GG.setCorFundo(FSys.COR_FUNDO_PADRAO);
        PCorGrid.setBackground(FSys.COR_GRID_PADRAO);
        GG.setCorGrid(FSys.COR_GRID_PADRAO);
        TFContX.setText("4");
        GG.setContX(4);
        TFContY.setText("4");
        GG.setContY(4);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
// TODO add your handling code here:
        DConfig.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void TBCirculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TBCirculoActionPerformed
// TODO add your handling code here:
        if( TBCirculo.isSelected() )
            GG.setTipoPontoComponente(COMPONENTE, Dado.CIRCLEF);
    }//GEN-LAST:event_TBCirculoActionPerformed

    private void TBQuadradoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TBQuadradoActionPerformed
// TODO add your handling code here:
        if( TBQuadrado.isSelected() )
            GG.setTipoPontoComponente(COMPONENTE, Dado.RECTF);
    }//GEN-LAST:event_TBQuadradoActionPerformed

    private void CBPontosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CBPontosActionPerformed
// TODO add your handling code here:
        GG.setVerPontosComponente(COMPONENTE, CBPontos.isSelected() ); 
    }//GEN-LAST:event_CBPontosActionPerformed

    private void CBLinhasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CBLinhasActionPerformed
// TODO add your handling code here:
        GG.setVerLinhasComponente(COMPONENTE, CBLinhas.isSelected() ); 
    }//GEN-LAST:event_CBLinhasActionPerformed

    private void PCorGrafMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PCorGrafMouseClicked
// TODO add your handling code here:
        DColor c = new DColor( FSys.getFramePrincipal() , true);
        FSys.centraliza(c);
        c.show();
        java.awt.Color cor = c.getCor();
        PCorGraf.setBackground(cor);
        if( COMPONENTE != null ) GG.setCorComponente(COMPONENTE,cor);
    }//GEN-LAST:event_PCorGrafMouseClicked

    private void CBMostrarGridActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CBMostrarGridActionPerformed
// TODO add your handling code here:
        GG.setVerGrid( CBMostrarGrid.isSelected() );
    }//GEN-LAST:event_CBMostrarGridActionPerformed

    private void CBExibirContYActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CBExibirContYActionPerformed
// TODO add your handling code here:
        GG.setVerNumY( CBExibirContY.isSelected() );
    }//GEN-LAST:event_CBExibirContYActionPerformed

    private void CBExibirContXActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CBExibirContXActionPerformed
// TODO add your handling code here:
        GG.setVerNumX( CBExibirContX.isSelected() );
    }//GEN-LAST:event_CBExibirContXActionPerformed

    private void TDadosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TDadosMouseClicked
// TODO add your handling code here:
        int row = TDados.getSelectedRow();
        boolean b = false;
        if( row >= 0 ) {
            b = true;
        } else {
            COMPONENTE = null;
            b = false;
        }

        CBLinhas.setEnabled(b);
        CBPontos.setEnabled(b);
        TBQuadrado.setEnabled(b);
        TBCirculo.setEnabled(b);
        PCorGraf.setEnabled(b);
        
        if( !b ) return;

        COMPONENTE = (String)TDados.getValueAt(row,0);
        PCorGraf.setBackground( GG.getCorComponente(COMPONENTE) );
        CBLinhas.setSelected( GG.verRetasComponente(COMPONENTE) );
        CBPontos.setSelected( GG.verPontosComponente(COMPONENTE) );
        TBQuadrado.setSelected( GG.getTipoPontoComponete(COMPONENTE) == Dado.RECTF ? true : false );
        TBCirculo.setSelected( GG.getTipoPontoComponete(COMPONENTE) == Dado.CIRCLEF ? true : false );
        GG.setCorComponente( COMPONENTE, PCorGraf.getBackground() );
    }//GEN-LAST:event_TDadosMouseClicked
    
    private void TFLabelYFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_TFLabelYFocusLost
// TODO add your handling code here:
        GG.setNameEixoY( TFLabelY.getText() );
        GG.repaint();
    }//GEN-LAST:event_TFLabelYFocusLost
    
    private void TFLabelXFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_TFLabelXFocusLost
// TODO add your handling code here:
        GG.setNameEixoX( TFLabelX.getText() );
        GG.repaint();
    }//GEN-LAST:event_TFLabelXFocusLost
    
    private void CBExibirLabelYActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CBExibirLabelYActionPerformed
// TODO add your handling code here:
        GG.setNameEixoY( TFLabelY.getText() );
        GG.setVerLabelY( CBExibirLabelY.isSelected() );
    }//GEN-LAST:event_CBExibirLabelYActionPerformed
    
    private void CBExibirLabelXActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CBExibirLabelXActionPerformed
// TODO add your handling code here:
        GG.setNameEixoX( TFLabelX.getText() );
        GG.setVerLabelX( CBExibirLabelX.isSelected() );
    }//GEN-LAST:event_CBExibirLabelXActionPerformed
    
    private void CBMostrarLegendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CBMostrarLegendaActionPerformed
// TODO add your handling code here:
        GG.setVerLegenda( CBMostrarLegenda.isSelected() );
    }//GEN-LAST:event_CBMostrarLegendaActionPerformed
    
    private void CBMostrarYActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CBMostrarYActionPerformed
// TODO add your handling code here:
        GG.setVerEixoY( CBMostrarY.isSelected() );
    }//GEN-LAST:event_CBMostrarYActionPerformed
    
    private void CBMostrarXActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CBMostrarXActionPerformed
// TODO add your handling code here:
        GG.setVerEixoX( CBMostrarX.isSelected() );
    }//GEN-LAST:event_CBMostrarXActionPerformed
    
    private void PCorGridMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PCorGridMouseClicked
// TODO add your handling code here:
        DColor c = new DColor( FSys.getFramePrincipal(), true);
        FSys.centraliza(c);
        c.show();
        java.awt.Color cor = c.getCor();
        PCorGrid.setBackground(cor);
        GG.setCorGrid( cor );
    }//GEN-LAST:event_PCorGridMouseClicked
    
    private void PCorFundoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PCorFundoMouseClicked
// TODO add your handling code here:
        DColor c = new DColor( FSys.getFramePrincipal() , true);
        FSys.centraliza(c);
        c.show();
        java.awt.Color cor = c.getCor();
        PCorFundo.setBackground(cor);
        GG.setCorFundo( cor );
    }//GEN-LAST:event_PCorFundoMouseClicked
    
    private void BExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BExcluirActionPerformed
// TODO add your handling code here:
        int row = TDados.getSelectedRow();
        if( row >= 0 ) {
            GG.RemovePlot( (String)modelo.getValueAt(row,0) );
            modelo.removeRow(row);
        }
        GG.repaint();
    }//GEN-LAST:event_BExcluirActionPerformed
    
    private void TBConfigActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TBConfigActionPerformed
// TODO add your handling code here:
        DConfig.setSize(530,380);
        FSys.centraliza(DConfig);
        DConfig.show();
        TBConfig.setSelected(false);
    }//GEN-LAST:event_TBConfigActionPerformed
    
    private void BAjustarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BAjustarActionPerformed
        // TODO add your handling code here:
        GG.AjusteInicial();
    }//GEN-LAST:event_BAjustarActionPerformed
    
    private void BAutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BAutoActionPerformed
        // TODO add your handling code here:
        GG.AutoAjuste();
    }//GEN-LAST:event_BAutoActionPerformed
    
    private void BSalvarGActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BSalvarGActionPerformed
        // TODO add your handling code here:
        JFileChooser f = new JFileChooser();
        //this.lista = lista;
        String extensao;
        JFrame J = new JFrame();
        f.setFileFilter(new FileFilter() //Filtro de exibição para extensão definida
        {
            public boolean accept(File f) {
                return f.getName().toLowerCase().endsWith(".eps")||
                        f.getName().toLowerCase().endsWith(".jpeg") || f.isDirectory();
            }
            public String getDescription() {
                return ".jpeg ou .eps";
            }
        });
        if(f.APPROVE_OPTION == f.showSaveDialog(J)) {
            File arquivo = f.getSelectedFile();
            
            FileFilter Filtro = f.getFileFilter();
            extensao = Filtro.getDescription();
            if ( arquivo == null || arquivo.getName().equals("") || arquivo.getName().trim().equals("") ) {
                JOptionPane.showMessageDialog(new JFrame(), "Nome de arquivo inválido",
                        "Nome de arquivo inválido", JOptionPane.ERROR_MESSAGE);
                return;
            }
            String caminho_config = new String(f.getSelectedFile().getPath());
            String caminho = new String(f.getSelectedFile().getPath());
            StringTokenizer str = new StringTokenizer(caminho,".");
            if(str.countTokens() == 1)//usuário não digitou extensão - jpeg é default
            {
                extensao = ".jpeg";
            } else {
                extensao = str.nextToken(); //pula o nome
                extensao = "."+str.nextToken();//pega a extensao
            }
            if( extensao.equals(".jpeg")) {
                leDisco disco = new leDisco();
                disco.salvaJPEG(this.getContentPane(), GG, caminho+extensao);
            } else if (extensao.equals(".eps")) {
                java.awt.Container cp = this.getContentPane();
                final java.awt.Component comp = cp.add(GG);
                javax.swing.JPanel south = new javax.swing.JPanel();
                try {
                    int w = comp.getWidth(), h = comp.getHeight();
                    java.awt.image.BufferedImage image = new java.awt.image.BufferedImage(w, h, java.awt.image.BufferedImage.TYPE_INT_RGB);
                    Componentes.Grafico.EpsGraphics2D g2 = new Componentes.Grafico.EpsGraphics2D(caminho, new FileOutputStream(caminho+extensao), 0, 0, w, h);
                    comp.paint(g2);
                    g2.dispose();
                } catch (IOException e) {
                    System.err.println(e);
                }
            } else {
                Sistema.FSys.Msg("Erro", "Esta versão suporta apenas imagens de extensão .jpeg e eps",0);
            }
        }
    }//GEN-LAST:event_BSalvarGActionPerformed
    
    private void BZoutVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BZoutVActionPerformed
        // TODO add your handling code here:
        GG.MenosZoomV();
    }//GEN-LAST:event_BZoutVActionPerformed
    
    private void BZinVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BZinVActionPerformed
        // TODO add your handling code here:
        GG.MaisZoomV();
    }//GEN-LAST:event_BZinVActionPerformed
    
    private void BZoutHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BZoutHActionPerformed
        // TODO add your handling code here:
        GG.MenosZoomH();
    }//GEN-LAST:event_BZoutHActionPerformed
    
    private void BZinHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BZinHActionPerformed
        // TODO add your handling code here:
        GG.MaisZoomH();
    }//GEN-LAST:event_BZinHActionPerformed
    
    private void BZoomOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BZoomOutActionPerformed
        // TODO add your handling code here:
        GG.MenosZoom();
    }//GEN-LAST:event_BZoomOutActionPerformed
    
    private void BZoomInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BZoomInActionPerformed
        // TODO add your handling code here:
        GG.MaisZoom();
    }//GEN-LAST:event_BZoomInActionPerformed
    
    private void BAntPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BAntPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BAntPActionPerformed
    
    public void setLabelPosMouse( Pontof p ) {
        java.text.DecimalFormat Form = new java.text.DecimalFormat("0.000");
        String Num1 = Form.format( p.x );
        String Num2 = Form.format( p.y );
        
        LabelPosMouse.setText(" Ponto ( "+Num1+" , "+Num2+" )");
    }
    
    public void Plot( Dado d ) {
        GG.Plot( d );
        modelo.addObjeto( d.getName() );
    }
    
    public String getName() {
        return Nome;
    }
    
    public void setName( String nome ) {
        this.Nome = nome;
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BAjustar;
    private javax.swing.JButton BAntP;
    private javax.swing.JButton BAuto;
    private javax.swing.JButton BExcluir;
    private javax.swing.JButton BProxP;
    private javax.swing.JButton BSalvarG;
    private javax.swing.JButton BZinH;
    private javax.swing.JButton BZinV;
    private javax.swing.JButton BZoomIn;
    private javax.swing.JButton BZoomOut;
    private javax.swing.JButton BZoutH;
    private javax.swing.JButton BZoutV;
    private javax.swing.JCheckBox CBExibirContX;
    private javax.swing.JCheckBox CBExibirContY;
    private javax.swing.JCheckBox CBExibirLabelX;
    private javax.swing.JCheckBox CBExibirLabelY;
    private javax.swing.JCheckBox CBLinhas;
    private javax.swing.JCheckBox CBMostrarGrid;
    private javax.swing.JCheckBox CBMostrarLegenda;
    private javax.swing.JCheckBox CBMostrarX;
    private javax.swing.JCheckBox CBMostrarY;
    private javax.swing.JCheckBox CBPontos;
    private javax.swing.JDialog DConfig;
    private javax.swing.JLabel LCorG1;
    private javax.swing.JLabel LLargG1;
    private javax.swing.JLabel LabelPosMouse;
    private javax.swing.JPanel PCentro;
    private javax.swing.JPanel PCorFundo;
    private javax.swing.JPanel PCorGraf;
    private javax.swing.JPanel PCorGrid;
    private javax.swing.JPanel PListaDados;
    private javax.swing.JPanel POutros;
    private javax.swing.JScrollPane SPDados;
    private javax.swing.JSeparator Separador0;
    private javax.swing.JSeparator Separador1;
    private javax.swing.JSeparator Separador2;
    private javax.swing.JSeparator Separador3;
    private javax.swing.JToggleButton TBCirculo;
    private javax.swing.JToggleButton TBConfig;
    private javax.swing.JToggleButton TBQuadrado;
    private javax.swing.JTable TDados;
    private javax.swing.JTextField TFContX;
    private javax.swing.JTextField TFContY;
    private javax.swing.JTextField TFLabelX;
    private javax.swing.JTextField TFLabelY;
    private javax.swing.JToolBar Toobar;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel;
    // End of variables declaration//GEN-END:variables
    
    private String COMPONENTE = null;
    private PanelGrafico GG;
    private String Nome;
    private ModeloTabelaLista modelo;
}