/*
 * IFMatriz.java
 *
 * Created on 3 de Março de 2005, 20:52
 */
package Janelas;
/**
 *
 * @author  Barnes
 */

import Componentes.Grafico.*;
import Dados.*;

public class IFResultado extends javax.swing.JInternalFrame {
    
    /** Creates new form IFMatriz */
    /*public IFResultado() {
        this("Grafico");
    }*/
    public IFResultado( String nome, String msg ) {
        this.Nome = nome;
        this.setTitle(nome);
        initVar();
        initComponents();
        Resultados.setText(msg);
        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        this.setSize(500,300);

        this.addInternalFrameListener( new javax.swing.event.InternalFrameAdapter() {
            public void windowClosing(javax.swing.event.InternalFrameEvent evt) {
                Sistema.FSys.Msg("","",0);
                dispose();
            }
        });        
    }

    private void initVar() {
        //LD = new Lista();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Código Gerado ">//GEN-BEGIN:initComponents
    private void initComponents() {
        Toobar = new javax.swing.JToolBar();
        BAbrirG = new javax.swing.JButton();
        Separador2 = new javax.swing.JSeparator();
        BSalvarG = new javax.swing.JButton();
        Separador1 = new javax.swing.JSeparator();
        BAntP = new javax.swing.JButton();
        Separador3 = new javax.swing.JSeparator();
        PCentro = new javax.swing.JPanel();
        spp = new javax.swing.JScrollPane();
        Resultados = new javax.swing.JTextArea();

        Toobar.setFloatable(false);
        BAbrirG.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagem/abrir.gif")));
        Toobar.add(BAbrirG);

        Separador2.setOrientation(javax.swing.SwingConstants.VERTICAL);
        Separador2.setMaximumSize(new java.awt.Dimension(1, 100));
        Toobar.add(Separador2);

        BSalvarG.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagem/salvar.gif")));
        Toobar.add(BSalvarG);

        Separador1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        Separador1.setToolTipText("");
        Separador1.setMaximumSize(new java.awt.Dimension(1, 150));
        Toobar.add(Separador1);

        BAntP.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagem/impressora.gif")));
        BAntP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BAntPActionPerformed(evt);
            }
        });

        Toobar.add(BAntP);

        Separador3.setOrientation(javax.swing.SwingConstants.VERTICAL);
        Separador3.setMaximumSize(new java.awt.Dimension(1, 100));
        Separador3.setPreferredSize(null);
        Toobar.add(Separador3);

        getContentPane().add(Toobar, java.awt.BorderLayout.NORTH);

        PCentro.setLayout(new java.awt.BorderLayout());

        spp.setViewportView(Resultados);

        PCentro.add(spp, java.awt.BorderLayout.CENTER);

        getContentPane().add(PCentro, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BAntPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BAntPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BAntPActionPerformed

    /*public void setLabelPosMouse( Pontof p )
    {
        java.text.DecimalFormat Form = new java.text.DecimalFormat("0.000");
        String Num1 = Form.format( p.x );
        String Num2 = Form.format( p.y );
    
        LabelPosMouse.setText(" Ponto ( "+Num1+" , "+Num2+" )");
    }

    public void Plot( Dado d ) {
        GG.Plot( d );
    }*/

    public String getName() {
        return Nome;
    }

    public void setName( String nome ) {
        this.Nome = nome;
    }

    // Declaração de variáveis - não modifique//GEN-BEGIN:variables
    private javax.swing.JButton BAbrirG;
    private javax.swing.JButton BAntP;
    private javax.swing.JButton BSalvarG;
    private javax.swing.JPanel PCentro;
    private javax.swing.JTextArea Resultados;
    private javax.swing.JSeparator Separador1;
    private javax.swing.JSeparator Separador2;
    private javax.swing.JSeparator Separador3;
    private javax.swing.JToolBar Toobar;
    private javax.swing.JScrollPane spp;
    // Fim da declaração de variáveis//GEN-END:variables

    private PanelGrafico GG;
    private String Nome;
}